import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';

// Explicit loopback test connections only; never fall back to DATABASE_URL/.env.
export function syntheticDatabaseUrl(value: string) {
  const url = new URL(value);
  assert.equal(url.protocol, 'postgresql:');
  assert.ok(['127.0.0.1', 'localhost'].includes(url.hostname));
  assert.equal(url.username, 'test');
  assert.ok(url.port, 'An explicit loopback test port is required');
  assert.match(url.pathname, /^\/checkout_http_recovery_[a-z0-9_]+$/);
  return url;
}

export async function createRecoveryDatabase(source: string, name: string) {
  const url = syntheticDatabaseUrl(source);
  assert.match(name, /^checkout_http_recovery_[a-z0-9_]{1,40}$/);
  const db = new PrismaClient({ datasources: { db: { url: url.href } } });
  try {
    // name is generated by the harness and strictly validated above.
    await db.$executeRawUnsafe(`CREATE DATABASE "${name}"`);
  } finally { await db.$disconnect(); }
  url.pathname = `/${name}`;
  return url.href;
}

export async function seedRecoveryFixture(connection: string, scenario: string) {
  const db = new PrismaClient({ datasources: { db: { url: syntheticDatabaseUrl(connection).href } } });
  try {
    assert.equal(await db.tenant.count(), 0, 'The new database must be empty');
    return await db.$transaction(async (tx) => {
      const tenant = await tx.tenant.create({ data: { name: 'Synthetic HTTP recovery', slug: 'default', plan: 'pro' } });
      const permission = await tx.permission.create({ data: { action: 'manage', resource: 'pos' } });
      const role = await tx.role.create({ data: { tenantId: tenant.id, name: 'Synthetic cashier', rolePermissions: { create: { permissionId: permission.id } } } });
      const staff = await tx.user.create({ data: {
        tenantId: tenant.id, email: `${scenario}@http-recovery.test`, passwordHash: 'not-a-login-hash',
        fullName: '合成 HTTP 收銀員', employeeCode: `HTTP-${scenario.toUpperCase()}`,
        userRoles: { create: { roleId: role.id } },
      } });
      await tx.customer.create({ data: { tenantId: tenant.id, phone: 'WALK_IN' } });
      const product = await tx.product.create({ data: {
        tenantId: tenant.id, sku: 'SYNTHETIC-HTTP', name: '合成 HTTP 恢復商品', retailPrice: 100, costPrice: 40, stockQuantity: 5,
      } });
      const batch = await tx.productBatch.create({ data: {
        tenantId: tenant.id, productId: product.id, batchNumber: 'SYNTHETIC-HTTP-LOT',
        quantity: 5, costPrice: 40, status: 'RELEASED', expiryDate: new Date('2099-01-01'),
      } });
      const shift = await tx.shift.create({ data: { tenantId: tenant.id, staffId: staff.id } });
      return { tenantId: tenant.id, staffId: staff.id, employeeCode: staff.employeeCode!, productId: product.id, batchId: batch.id, shiftId: shift.id, initialStock: 5, saleQuantity: 2 };
    });
  } finally { await db.$disconnect(); }
}

export type RecoveryFixture = Awaited<ReturnType<typeof seedRecoveryFixture>>;

export async function recoverySnapshot(connection: string, fixture: RecoveryFixture) {
  const db = new PrismaClient({ datasources: { db: { url: syntheticDatabaseUrl(connection).href } } });
  const tenantId = fixture.tenantId;
  try {
    const [database, product, batch, orders, payments, movements, allocations, commands] = await db.$transaction([
      db.$queryRaw`SELECT current_database() AS name, inet_server_addr()::text AS host, inet_server_port() AS port, version() AS version, pg_postmaster_start_time() AS started_at`,
      db.product.findUniqueOrThrow({ where: { id: fixture.productId }, select: { id: true, stockQuantity: true } }),
      db.productBatch.findUniqueOrThrow({ where: { id: fixture.batchId }, select: { id: true, quantity: true } }),
      db.order.findMany({ where: { tenantId }, select: { id: true, orderNumber: true, items: { select: { id: true, productId: true, quantity: true } } } }),
      db.orderPayment.findMany({ where: { tenantId }, select: { id: true, orderId: true, method: true, amount: true } }),
      db.inventoryTransaction.findMany({ where: { tenantId }, select: { id: true, productId: true, type: true, referenceId: true, quantity: true } }),
      db.saleBatchAllocation.findMany({ where: { tenantId }, select: { id: true, orderId: true, orderItemId: true, productId: true, batchId: true, movementId: true, quantity: true } }),
      db.checkoutCommand.findMany({ where: { tenantId }, select: { commandId: true, kind: true, status: true, orderId: true, payloadHash: true, result: true } }),
    ]);
    // Decimal/Date values become the same JSON types as the HTTP wire result.
    return JSON.parse(JSON.stringify({ database, product, batch, orders, payments, movements, allocations, commands })) as {
      database: { name: string; host: string; port: number; version: string; started_at: string }[];
      product: { id: string; stockQuantity: number }; batch: { id: string; quantity: number };
      orders: { id: string; orderNumber: string; items: { id: string; productId: string; quantity: number }[] }[];
      payments: { id: string; orderId: string; method: string; amount: string }[];
      movements: { id: string; productId: string; type: string; referenceId: string; quantity: number }[];
      allocations: { id: string; orderId: string; orderItemId: string; productId: string; batchId: string; movementId: string; quantity: number }[];
      commands: { commandId: string; kind: string; status: string; orderId: string; payloadHash: string; result: unknown }[];
    };
  } finally { await db.$disconnect(); }
}
